name: Push Docker image

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/push_docker.yaml'
      - 'pegasus/**'
      - 'scripts/**'
      - 'sharegpt/**'
      - 'Dockerfile'
      - 'LICENSE'
      - 'requirements-benchmark.txt'
      - '.gitignore'

concurrency:
  group: ${{ github.ref }}-dhpush
  cancel-in-progress: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mlenergy/leaderboard
          tags: latest
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=mlenergy/leaderboard:buildcache
          cache-to: type=registry,ref=mlenergy/leaderboard:buildcache,mode=max
